[kdc]
kdc1 ansible_host=192.168.56.11

[namenode]
nn1 ansible_host=192.168.56.12

[prod]
prod1 ansible_host=192.168.56.13

[dr]
dr1 ansible_host=192.168.56.14

[router]
router1 ansible_host=192.168.56.15

[hadoop:children]
namenode
prod
dr
router

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key
ansible_python_interpreter=/usr/bin/python3
