[libdefaults]
    default_realm = EXAMPLE.COM
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false
    udp_preference_limit = 1
    default_ccache_name = KEYRING:persistent:%{uid}

[realms]
    EXAMPLE.COM = {
        kdc = kdc1.lab.example.com
        admin_server = kdc1.lab.example.com
    }

[domain_realm]
    .lab.example.com = EXAMPLE.COM
    lab.example.com = EXAMPLE.COM
